language: java
jdk:
- openjdk8

addons:
  sonarcloud:
    organization: "ultrale"
    token: d09bef22ab70cd3ac1440756814902d7abf4d102

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  #- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
  #- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent verify sonar:sonar -Dsonar.projectKey=