language: java
jdk:
- openjdk8

addons:
  sonarcloud:
    organization: "ultrale"
    token: 82d34af42e85f61618c022468d0ccf43338d38b5

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent verify org.pitest:pitest-maven:mutationCoverage sonar:sonar -Dsonar.projectKey=UltraLe_JacocoBaduaPit
  #- mvn clean verify sonar:sonar -Dsonar.projectKey=UltraLe_JacocoBaduaPit